name: chat_allamo
description: "A new Flutter project."
publish_to: "none"
version: 0.2.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  custom_sliding_segmented_control: ^1.8.3
  firebase_core: ^3.0.0
  firebase_storage: ^12.0.0
  fluentui_system_icons: ^1.1.241
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_highlight: ^0.7.0
  flutter_highlighting: ^0.9.0+11.8.0
  flutter_markdown: ^0.7.1
  flutter_native_splash: ^2.4.0
  flutter_settings_ui: ^3.0.1
  flutter_zoom_drawer: ^3.2.0
  fluttertoast: ^8.2.6
  go_router: ^14.1.4
  google_nav_bar: ^5.0.6
  highlight: ^0.7.0
  image_picker: ^1.1.2
  internet_connection_checker_plus: ^2.4.1
  intl: ^0.19.0
  markdown: ^7.2.2
  modal_bottom_sheet: ^3.0.0
  ollama_dart: ^0.1.1
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  sqflite_common_ffi: ^2.3.3
  sqlite3_flutter_libs: ^0.5.23
  super_cupertino_navigation_bar: ^2.1.2
  url_launcher: ^6.3.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21
